### ISSUE TITLE
Design Logo

### ISSUE THREAD

**Issue by cameskridge** [TeamGeoCTW/Attend-In#29]

**Comment by ekelley8** [comment]
![Attend-In Real Logo](https://user-images.githubusercontent.com/43686462/65835817-c9434680-e2b8-11e9-993b-1146d1c056fd.png)
![Attend-In Logo on phone](https://user-images.githubusercontent.com/43686462/65835820-cd6f6400-e2b8-11e9-8196-bb6bf890d38c.JPG)
