### ISSUE TITLE
MVC (Model-View-Controller) Architectural pattern

### ISSUE THREAD

**Issue by Hard-Thakkar** [TeamGeoCTW/Attend-In#38]

**Comment by ekelley8** [comment]
![MVC (as of now)](https://user-images.githubusercontent.com/43686462/67126644-95778480-f1c5-11e9-9bde-861989dba652.jpeg)
![Planned MVC Model](https://user-images.githubusercontent.com/43686462/67126650-990b0b80-f1c5-11e9-8fc5-5b2cdf83807c.jpeg)
