### ISSUE TITLE
Object Class Model

### ISSUE THREAD

**Issue by Hard-Thakkar** [TeamGeoCTW/Attend-In#41]
Create a structural pattern showing all methods, objects and variables in use including all the java files

**Comment by hardthakkar123** [comment]
Create a structural pattern showing all methods, objects and variables in use including all the java files

**Comment by ekelley8** [comment]
![Object Class Model](https://user-images.githubusercontent.com/43686462/67126548-58ab8d80-f1c5-11e9-9605-2cbcd2975897.JPG)
